@startmindmap
* Document content
** Medical examination
*** Type of examination
*** Date of issue
** Medical assessment
*** Type of assessment
*** Date of validity
*** Date of issue
** Result
*** Medical fitness
*** Restrictions
*** Justification
@endmindmap
